version: "3.7"

services:
  principal-web:
    image: ghcr.io/desarrolloqsn/pagina-qsocial/main/pagina-qsocial:latest
    container_name: principal-web
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=${HOST_DNS}
      - VIRTUAL_PATH=/
    volumes:
      - ./volumes/principal-web:/data
    networks:
      qsn_net:
        ipv4_address: 192.168.3.49

  servidor-mapas:
    image: nginx
    container_name: servidor-mapas
    restart: on-failure
    command: >
      sh -c "chown nginx:nginx -R /usr/share/nginx/html && nginx -g 'daemon off;'"
    ports:
      - 8081:80
    environment:
      - VIRTUAL_HOST=${HOST_DNS}
      - VIRTUAL_PATH=/mapas
      - VIRTUAL_DEST=/
    volumes:
      - /home/qsnftp/static-principal-page:/usr/share/nginx/html
      - ./nginx/autoindex_settings.conf:/etc/nginx/conf.d/autoindex_settings.conf
    networks:
      qsn_net:
        ipv4_address: 192.168.3.50

  auth:
    image: ghcr.io/qsn-desarrollo/apiauth/main/apiauth:latest
    container_name: auth
    restart: on-failure
    environment:
      - DB_ENGINE=mariadb
      - MARIADB_HOST=${MARIADB_HOST_PROD}
      - MARIADB_PORT=3306
      - MARIADB_USER_QSN=${MARIADB_USER_QSN}
      - MARIADB_PASS_QSN=${MARIADB_PASS_QSN}
      - MARIADB_DB_QSN=${MARIADB_DB_QSN}
      - API_AUTH_PORT=3000
      - VIRTUAL_HOST=${API_HOST_DNS}
      - VIRTUAL_PATH=/auth/
      - LETSENCRYPT_HOST=${API_HOST_DNS}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ENVIRONMENT=${VIRTUAL_HOST}
      - EMAIL_SEND=${EMAIL_SEND}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - REDIRECT_CHANGE_PASSWORD=${REDIRECT_CHANGE_PASSWORD}
    ports:
      - 3000:3000
    networks:
      qsn_net:
        ipv4_address: 192.168.3.10

  minidash:
    image: ghcr.io/qsn-desarrollo/apiminidash/main/apiminidash:latest
    container_name: minidash
    restart: on-failure
    environment:
      - DB_ENGINE=mariadb
      - MARIADB_HOST=${MARIADB_HOST_PROD}
      - MARIADB_PORT=3306
      - MARIADB_USER_QSN=${MARIADB_USER_QSN}
      - MARIADB_PASS_QSN=${MARIADB_PASS_QSN}
      - MARIADB_DB_QSN=${MARIADB_DB_QSN}
      - API_MINIDASH_PORT=3001
      - VIRTUAL_HOST=${API_HOST_DNS}
      - VIRTUAL_PATH=/miniDash/
    ports:
      - 3001:3001
    networks:
      qsn_net:
        ipv4_address: 192.168.3.11

  datostest:
    image: ghcr.io/qsn-desarrollo/apidatostest/main/apidatostest:latest
    container_name: datostest
    restart: on-failure
    environment:
      - DB_ENGINE=mongodb
      - MONGODB_HOST=${MONGODB_HOST_PROD}
      - MONGODB_PORT=${MONGODB_PORT_PROD}
      - MONGODB_USER_REDES=${MONGODB_USER_QSN}
      - MONGODB_PASS_REDES=${MONGODB_PASS_QSN}
      - MONGODB_DB_REDES=${MONGODB_DB_REDES}
      - MONGODB_AUTHSOURCE=admin
      - MONGODB_AUTHTECH=SCRAM-SHA-1
      - API_DATOSTEST_PORT=3002
      - NODE_OPTIONS=--max-old-space-size=8192
      - VIRTUAL_HOST=${API_HOST_DNS}
      - VIRTUAL_PATH=/datostest/
      # - VIRTUAL_DEST=/
    ports:
      - 3002:3002
    networks:
      qsn_net:
        ipv4_address: 192.168.3.12

  instagram:
    image: ghcr.io/qsn-desarrollo/apiinstagram/main/apiinstagram:latest
    container_name: instagram
    restart: on-failure
    environment:
      - API_IG_PORT=3003
      - VIRTUAL_HOST=${API_HOST_DNS}
      - VIRTUAL_PATH=/generateBase64/
      # - VIRTUAL_DEST=/
    ports:
      - 3003:3003
    networks:
      qsn_net:
        ipv4_address: 192.168.3.13

  bucket:
    image: ghcr.io/qsn-desarrollo/apibucket/main/apibucket:latest
    container_name: bucket
    restart: on-failure
    environment:
      - API_BUCKET_PORT=3004
      - FTP_HOST=${FTP_HOST_PROD}
      - FTP_PORT=${FTP_PORT_PROD}
      - FTP_USER=${FTP_USER_PROD}
      - FTP_PASS=${FTP_PASS_PROD}
      - VIRTUAL_HOST=${API_HOST_DNS}
      - VIRTUAL_PATH=/bucket/
      # - VIRTUAL_DEST=/
    ports:
      - 3004:3004
    networks:
      qsn_net:
        ipv4_address: 192.168.3.14

  dashboard_backend:
    image: ghcr.io/qsn-desarrollo/apidashboard/main/apidashboard:latest
    container_name: dashboard_backend
    restart: on-failure
    environment:
      - DB_ENGINE=mariadb
      - MARIADB_HOST=${MARIADB_HOST_PROD}
      - MARIADB_PORT=${MARIADB_PORT_PROD}
      - MARIADB_USER_QSN=${MARIADB_USER_QSN}
      - MARIADB_PASS_QSN=${MARIADB_PASS_QSN}
      - MARIADB_DB_QSN=${MARIADB_DB_QSN}
      - API_DASH_PORT=3005
      - VIRTUAL_HOST=${API_HOST_DNS}
      - VIRTUAL_PATH=/Dashboard/
      # - VIRTUAL_DEST=/
    ports:
      - 3005:3005
    networks:
      qsn_net:
        ipv4_address: 192.168.3.15

  web_app:
    image: ghcr.io/qsn-desarrollo/listening_my_new/main/listening_my_new:latest
    container_name: web_app
    restart: on-failure
    environment:
      # - PORT=3000
      # - REACT_APP_ENDPOINT_API=${API_HOST_DNS}
      - VIRTUAL_HOST=${HOST_DNS}
      - VIRTUAL_PATH=/app
      - LETSENCRYPT_HOST=${HOST_DNS}
      - NODE_OPTIONS=--max-old-space-size=8192
    ports:
      - 8084:3000
    networks:
      qsn_net:
        ipv4_address: 192.168.3.16
networks:
  qsn_net:
    name: qsn_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.3.0/24"
