version: "3.7"

services:
  principal-web:
    image: ghcr.io/desarrolloqsn/pagina-qsocial/main/pagina-qsocial:latest
    container_name: principal-web
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=${HOST_DNS}
      - VIRTUAL_PATH=/
    volumes:
      - ./volumes/principal-web:/data
    networks:
      qsn_net:
        ipv4_address: 192.168.3.49

  servidor-mapas:
    image: nginx
    container_name: servidor-mapas
    restart: on-failure
    command: "chown nginx:nginx -R /usr/share/nginx/html && nginx -g daemon off;"
    ports:
      - 8081:80
    environment:
      - VIRTUAL_HOST=${HOST_DNS}
      - VIRTUAL_PATH=/mapas
      - VIRTUAL_DEST=/
    volumes:
      - /home/qsnftp/static-principal-page:/usr/share/nginx/html
    networks:
      qsn_net:
        ipv4_address: 192.168.3.50

networks:
  qsn_net:
    name: qsn_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.3.0/24"
